#!/bin/bash

cd ~

backupFile=$HOSTNAME"_"$(date +%F)".tar.gz"

tar -cpzf $backupFile Documents Downloads Music Pictures Repos Videos
# Restore with
# sudo tar -xpzf $backupFile [-C /directory/to/extract/to] --numeric-owner

aws s3 mv $backupFile ryanmalkinpcbackups
