#!/bin/bash

cd ~

backupFile=$HOSTNAME"_"$(date +%F)".tar.gz"

tar -cpzf $backupFile Documents Downloads Music Pictures Repos Videos
# Restore by running the following from a clean home directory:
# sudo tar -xpzf $backupFile

aws s3 mv $backupFile s3://ryanmalkinpcbackups
