#!/bin/bash

echo "Start"

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

./subroutines/update
./subroutines/snaps/installSnaps
./subroutines/apts/installApts
./subroutines/manualInstalls
./subroutines/repos
./subroutines/configs $SCRIPT_DIR
./subroutines/backups/setup $SCRIPT_DIR

echo "Complete"
echo "Remember to set up AWS CLI and backup cron job"
