#!/bin/bash

echo "Start"

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

sudo ./subroutines/update
sudo ./subroutines/snaps/installSnaps
sudo ./subroutines/apts/installApts
./subroutines/pips/installPips
sudo ./subroutines/manualInstalls
./subroutines/configs $SCRIPT_DIR
./subroutines/backups/setup $SCRIPT_DIR

echo "Complete"
echo "Remember to set up AWS CLI and backup cron job"
