#!/bin/bash

echo "---------- APTS START ----------"

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

while read line; do
    app=$(echo $line | sed 's/ .*//')
    if ! dpkg -s $app &>/dev/null; then
        echo "Installing $app"
        sudo apt-get -y install $line 2>&1 1>/dev/null
    else
        echo "Skipping $app, already installed"
    fi
done < $SCRIPT_DIR/apts.txt

echo "---------- APTS COMPLETE ----------"
