#!/bin/bash

echo "---------- APTS ----------"

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

while read line; do
    app=$(echo $line | sed 's/ .*//')
    if ! dpkg -s $app &>/dev/null; then
        echo "Installing "$app
        apt -y install $line
    else
        echo "Skipping "$app", already installed"
    fi
done < $SCRIPT_DIR"/apts.txt"

echo "---------- APTS COMPLETE ----------"
