#!/bin/bash
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

while read line; do
	app=$(echo "$line" | sed 's/ .*//')
	if ! command -v $app >/dev/null; then
		snap install $line
	fi
done < $SCRIPT_DIR"/snaps.txt"
