#!/bin/bash

echo "---------- SNAPS START ----------"

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

while read line; do
    app=$(echo "$line" | sed 's/ .*//')
    if ! snap list $app &>/dev/null; then
        echo "Installing "$line
        snap install $line
    else
        echo "Skipping "$line", already installed"
    fi
done < $SCRIPT_DIR"/snaps.txt"

echo "---------- SNAPS COMPLETE ----------"
