#!/bin/bash
SCRIPT_DIR="(dirname "$(readlink -f "$0")")"

while read line; do
    line=$(echo $line | sed 's/ .*//')
    app=
    package=
    if ! dpkg -s $app $>/dev/null; then 
        echo "Installing "$app
        #do stuff
    else
        echo "Skipping "$app", already installed"
    fi
done < $SCRIPT_DIR"/wgets.txt"
