#!/bin/bash

echo "---------- PIPS ------------"

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

while read line; do
    app=$(echo $line | sed 's/ .*//')
    if ! pip3 show $app &>/dev/null; then
        echo "Installing "$app
        pip3 install $app
    else
        echo "Skipping "$app", already installed"
    fi
done <$SCRIPT_DIR"/pips.txt"

echo "---------- PIPS COMPLETE ----------"
