#!/bin/bash

backupOldConfig () {
    if test -f $1; then
        mv $1 $1.old
    fi
}

echo "---------- CONFIGS START ----------"

PROJECT_DIR=$1
CONFIGS_SUBMODULE_DIR=$PROJECT_DIR"/Configs"

echo "Git"
GIT_CONFIG_DIR=$HOME/.config/git
GIT_CONF=$GIT_CONFIG_DIR/config
mkdir --parents $GIT_CONFIG_DIR
backupOldConfig $GIT_CONF
backupOldConfig $HOME/.gitconfig
echo "[include]" > $GIT_CONF
echo "    path = $CONFIGS_SUBMODULE_DIR/.gitconfig" >> $GIT_CONF

echo "Set up Git repos"
REPOS_DIR=$HOME/Repos
mkdir --parents $REPOS_DIR
CONFIGS_REPO=$REPOS_DIR/Configs
if ! test -d $CONFIGS_REPO; then
    git clone https://github.com/FubarBazquux/Configs.git $CONFIGS_REPO
fi
RESTOREUBUNTU_REPO=$REPOS_DIR/RestoreUbuntu
if ! test -d $RESTOREUBUNTU_REPO; then
    git clone https://github.com/FubarBazquux/RestoreUbuntu.git $RESTOREUBUNTU_REPO
fi

echo "Bash"
BASHRC=$HOME/.bashrc
backupOldConfig $BASHRC
echo "source $CONFIGS_SUBMODULE_DIR/.bashrc.common" > $BASHRC

echo "Tmux"
TMUX_CONFIG_DIR=$HOME/.config/tmux
TMUX_CONF=$TMUX_CONFIG_DIR/tmux.conf
mkdir --parents $TMUX_CONFIG_DIR
backupOldConfig $TMUX_CONF
echo "source-file $CONFIGS_SUBMODULE_DIR/.tmux.conf.common" > $TMUX_CONF

echo "Vim"
VIMRC=$HOME"/.vimrc"
backupOldConfig $VIMRC
echo "source $CONFIGS_SUBMODULE_DIR/.vimrc.common" > $VIMRC

echo "Nvim"
NVIM_CONFIG_DIR=$HOME"/.config/nvim"
NVIM_INIT=$NVIM_CONFIG_DIR/init.vim
mkdir --parents $NVIM_CONFIG_DIR
backupOldConfig $NVIM_INIT
echo "source $VIMRC" > $NVIM_INIT

echo "---------- CONFIGS END ---------"
