#!/bin/bash

echo "---------- MANUAL INSTALLS START ----------"

# AWS CLI
if ! which aws &>/dev/null; then
    echo "Installing AWS CLI"
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    rm awscliv2.zip
    rm -r aws
else
    echo "Skipping AWS CLI, already installed"
fi

# Chrome
if ! dpkg -s google-chrome-stable &>/dev/null; then
    echo "Installing Chrome"
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 1>/dev/null
    apt install -y ./google-chrome-stable_current_amd64.deb 1>/dev/null
    rm google-chrome-stable_current_amd64.deb
else
    echo "Skipping Chrome, already installed"
fi

# psensor
if ! dpkg -s psensor &>/dev/null; then
    echo "Installing psensor"
    if ! dpkg -s lm-sensors &>/dev/null; then
        echo "Installing lm-sensors"
        apt install -y lm-sensors 1>/dev/null
        sensors-detect
    else
        echo "Skipping lm-sensors, already installed"
    fi
    apt install -y psensor 1>/dev/null
else
    echo "Skipping psensor, already installed"
fi

# Zoom
if ! dpkg -s zoom &>/dev/null; then
    echo "Installing Zoom"
    wget https://zoom.us/client/latest/zoom_amd64.deb 1>/dev/null
    apt install -y ./zoom_amd64.deb 1>/dev/null
    rm zoom_amd64.deb
else
    echo "Skipping Zoom, already installed"
fi

# Mega
if ! dpkg -s megasync &>/dev/null; then
    echo "Installing Mega"
    wget https://mega.nz/linux/MEGAsync/xUbuntu_20.04/amd64/megasync-xUbuntu_20.04_amd64.deb 1>/dev/null
    apt install -y ./megasync-xUbuntu_20.04_amd64.deb 1>dev/null
    rm megasync-xubuntu_20.04_amd64.deb
else
    echo "Skipping Mega, already installed"
fi

if ! dpkg -s nautilus-megasync &>/dev/null; then
    echo "Installing Mega Nautilus plugin"
    wget https://mega.nz/linux/MEGAsync/xUbuntu_20.04/amd64/nautilus-megasync-xUbuntu_20.04_amd64.deb 1>/dev/null
    apt install -y ./nautilus-megasync-xUbuntu_20.04_amd64.deb 1>/dev/null
    rm nautilus-megasync-xUbuntu_20.04_amd64.deb
else
    echo "Skipping Mega Nautilus plugin, already installed"
fi

# Steam
if ! dpkg -s steam-launcher &>/dev/null; then
    echo "Installing Steam"
    wget https://steamcdn-a.akamaihd.net/client/installer/steam.deb 1>/dev/null
    apt install -y ./steam.deb 1>/dev/null
    rm steam.deb
else
    echo "Skipping Steam, already installed"
fi

# Sublime
if ! dpkg -s sublime-text &>/dev/null; then
    echo "Installing Sublime"
    wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
    echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list
    apt update 1>/dev/null
    apt install -y sublime-text 1>/dev/null
else
    echo "Skipping Sublime, already installed"
fi

# Wavebox
if ! dpkg -s wavebox &>/dev/null; then
    echo "Installing Wavebox"
    wget https://download.wavebox.app/latest/stable/linux/deb
    mv deb wavebox.deb
    apt install -y ./wavebox.deb 1>/dev/null
    rm wavebox.deb
else
    echo "Skipping Wavebox, already installed"
fi

# Wine
if ! dpkg -s winehq-stable &>/dev/null; then
    echo "Installing Wine"
    wget -O - https://dl.winehq.org/wine-builds/winehq.key | apt-key add -
    add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main' 1>/dev/null
    apt update 1>/dev/null
    apt install -y --install-recommends winehq-stable 1>/dev/null
else
    echo "Skipping Wine, already installed"
fi

# Veracrypt
if ! dpkg -s veracrypt &>/dev/null; then
    echo "Installing Veracrypt"
    wget https://launchpad.net/veracrypt/trunk/1.24-update4/+download/veracrypt-1.24-Update4-Ubuntu-20.04-amd64.deb 1>/dev/null
    apt install -y ./veracrypt-1.24-Update4-Ubuntu-20.04-amd64.deb 1>/dev/null
    rm veracrypt-1.24-Update4-Ubuntu-20.04-amd64.deb
else
    echo "Skipping Veracrypt, already installed"
fi

echo "---------- MANUAL INSTALLS COMPLETE ----------"
