#!/bin/bash

echo "---------- MANUAL INSTALLS START ----------"

# Chrome
if ! dpkg -s google-chrome-stable &>/dev/null; then
    echo "Installing Chrome"
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 1>/dev/null
    sudo apt-get install -y ./google-chrome-stable_current_amd64.deb 1>/dev/null
    rm google-chrome-stable_current_amd64.deb
else
    echo "Skipping Chrome, already installed"
fi

# Syncthing
if ! dpkg -s syncthing &>/dev/null; then
    echo "Installing Syncthing"
    mkdir -p /etc/apt/keyrings
    sudo curl -L -o /etc/apt/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg
    echo "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list
    sudo apt-get update 1>/dev/null
    sudo apt-get install -y syncthing 1>/dev/null
else
    echo "Skipping Syncthing, already installed"
fi

# Wavebox
if ! dpkg -s wavebox &>/dev/null; then
    echo "Installing Wavebox"
    wget https://download.wavebox.app/latest/stable/linux/deb
    mv deb wavebox.deb
    sudo apt-get install -y ./wavebox.deb 1>/dev/null
    rm wavebox.deb
else
    echo "Skipping Wavebox, already installed"
fi

echo "---------- MANUAL INSTALLS COMPLETE ----------"
