#!/bin/bash

echo "---------- REPOS START ----------"

echo "Configs"
CONFIGS_REPO=$HOME/Repos/Configs
if ! test -d $CONFIGS_REPO; then
    git clone https://github.com/FubarBazquux/Configs.git $CONFIGS_REPO 2>&1 1>/dev/null
fi

echo "---------- REPOS END ----------"
